Alas:
  global_bind: true
  groups:
    - Game
  displays:
    - Game
    - { task: Device, group: Emulator }
    - { task: Device, group: EmulatorInfo }
    - { task: Device, group: Error }
    - { task: Device, group: Optimization }

RestartDeviceDisplay:
  displays:
    - info: RestartDevice
      groups: { task: RestartDevice, group: Scheduler }

RestartGameDisplay:
  displays:
    - info: RestartGame
      groups: { task: RestartGame, group: Scheduler }
