OpsiExplore:
  groups:
    - Scheduler
    - OpsiExplore
  displays: flat

#  default:
#    Scheduler:
#      Enable: true
#  override:
#    OpsiExplore:
#      SpecialRadar: false
#  trigger:
#    on:
#      - OpsiExplore.OpsiExplore.SpecialRadar == true
#    set:
#  trigger_show: OpsiExplore.OpsiExplore.SpecialRadar == true

OpsiDaily:
  groups:
    - Scheduler
    - OpsiDaily
    - task: OpsiGeneral
      group: OpsiGeneral
  displays: flat

OpsiGeneral:
  groups:
    - OpsiGeneral

OpsiAshAssist:
  groups:
    - Scheduler
    - OpsiAshAssist
  displays: flat
