Main:
  groups:
    - Scheduler
    - Campaign
    - StopCondition
    - Fleet1
    - Fleet2
    - Submarine
    - Emotion
    - HpControl
    - EnemyPriority
  displays:
    - info: Main
      groups: Scheduler
    - Campaign
    - StopCondition
    - info: Fleet
      groups: [ Fleet1, Fleet2 ]
    - Submarine
    - Emotion
    - HpControl
    - EnemyPriority
